[package]
name = "globwalk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob-match = { version = "0.2.1", path = "../glob-match" }
turbopath = { path = "../turbopath" }
walkdir = "2.3.3"
