name: "Setup Turborepo Environment"
description: "Sets up development environment for turborepo"
inputs:
  target:
    description: "Compilation target"
    required: true
  github-token:
    description: "GitHub token. You can pass secrets.GITHUB_TOKEN"
    required: true
  setup-rust:
    description: "Install Rust toolchain to build Turborepo"
    required: false
    type: boolean
    default: true
  setup-go:
    description: "Install Go toolchain to build Turborepo"
    required: false
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
    - name: "Setup Node"
      uses: ./.github/actions/setup-node

    - name: "Setup Go"
      if: inputs.setup-go == 'true'
      uses: ./.github/actions/setup-go
      with:
        github-token: ${{ inputs.github-token }}

    - name: "Setup Rust"
      if: inputs.setup-rust == 'true'
      uses: ./.github/actions/setup-rust
      with:
        target: ${{ inputs.target }}
        shared-cache-key: turborepo-debug-build
        cache-key: ${{ inputs.target }}
        save-cache: true

    - name: "Setup capnproto for ubuntu"
      if: inputs.target == 'ubuntu'
      shell: bash
      run: sudo apt-get update && sudo apt-get install capnproto

    - name: "Setup capnproto for macos"
      if: inputs.target == 'macos'
      shell: bash
      run: brew install capnp

    - name: "Setup capnproto for Windows"
      if: inputs.target == 'windows'
      shell: bash
      run: choco install capnproto

    - name: Install Turbo globally
      shell: bash
      run: |
        VERSION=$(npm view turbo --json | jq -r '.versions | last')
        echo "Latest published version: $VERSION"
        npm i -g turbo@$VERSION
