# Once you push this code to a repo on GitHub, Dependabot will automatically start sending PRs to keep your dependencies up-to-date!
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/packages/create-turbo'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/packages/turbo-codemod'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/packages/turbo-ignore'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/docs'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/benchmark'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/cli'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'gomod'
    directory: '/cli'
    schedule:
      interval: 'monthly'
