# Used to auto generate turborepo release notes

changelog:
  exclude:
    labels:
      - "team: turbopack"
      - "area: ci"
  categories:
    - title: Docs
      labels:
        - "area: docs"
        - "area: site"
    - title: create-turbo
      labels:
        - "pkg: create-turbo"
    - title: turbo-ignore
      labels:
        - "pkg: turbo-ignore"
    - title: "@turbo/codemod"
      labels:
        - "pkg: turbo-codemod"
    - title: "eslint"
      labels:
        - "pkg: turbo-eslint"
    - title: Examples
      labels:
        - "area: examples"
    - title: Changelog
      labels:
        - "*"
