[package]
name = "turborepo-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
native-tls = ["turborepo-api-client/native-tls"]
rustls-tls = ["turborepo-api-client/rustls-tls"]


[dev-dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
env_logger = "0.10.0"
tempfile = { workspace = true }

[dependencies]
base64 = "0.21.0"
bytes.workspace = true
chrono = { workspace = true }
dunce = { workspace = true }
lazy_static = { workspace = true }
log.workspace = true
os_str_bytes = "6.5.0"
ring = "0.16.20"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tar = "0.4.38"
test-log = "0.2.11"
thiserror = { workspace = true }
turbopath = { workspace = true }
turborepo-api-client = { workspace = true }
zstd = "0.12.3"
