[package]
name = "turbopack-trace-server"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"
autobenches = false

[[bin]]
name = "turbo-trace-server"
path = "src/main.rs"
bench = false

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
either = { workspace = true }
flate2 = { version = "1.0.28" }
indexmap = { workspace = true, features = ["serde"] }
itertools = { workspace = true }
postcard = { workspace = true }
rustc-demangle = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
turbopack-trace-utils = { workspace = true }
websocket = { version = "0.27.0", features = ["sync"] }
zstd = { version = "0.13.0" }
