project_name: turbo
before:
  hooks:
    - go mod tidy
    - make compile-protos
    # Each package.json needs to be updated.
    - cmd: npm version "{{ .Version }}" --allow-same-version
      dir: npm/turbo-android-arm64
    - cmd: npm version "{{ .Version }}" --allow-same-version
      dir: npm/turbo-darwin-64
    - cmd: npm version "{{ .Version }}" --allow-same-version
      dir: npm/turbo-darwin-arm64
    - cmd: npm version "{{ .Version }}" --allow-same-version
      dir: npm/turbo-freebsd-64
    - cmd: npm version "{{ .Version }}" --allow-same-version
      dir: npm/turbo-freebsd-arm64
    - cmd: npm version "{{ .Version }}" --allow-same-version
      dir: npm/turbo-linux-32
    - cmd: npm version "{{ .Version }}" --allow-same-version
      dir: npm/turbo-linux-64
    - cmd: npm version "{{ .Version }}" --allow-same-version
      dir: npm/turbo-linux-arm
    - cmd: npm version "{{ .Version }}" --allow-same-version
      dir: npm/turbo-linux-arm64
    - cmd: npm version "{{ .Version }}" --allow-same-version
      dir: npm/turbo-linux-mips64le
    - cmd: npm version "{{ .Version }}" --allow-same-version
      dir: npm/turbo-linux-ppc64le
    - cmd: npm version "{{ .Version }}" --allow-same-version
      dir: npm/turbo-windows-32
    - cmd: npm version "{{ .Version }}" --allow-same-version
      dir: npm/turbo-windows-64
    - cmd: npm version "{{ .Version }}" --allow-same-version
      dir: npm/turbo-windows-arm64
builds:
  - id: turbo
    main: ./cmd/turbo
    binary: bin/turbo
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    targets:
      - android_arm64
      - freebsd_amd64
      - freebsd_arm64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - linux_mips64le
      - linux_ppc64le
      - windows_386
      - windows_amd64
      - windows_arm64
  - id: turbo-cgo
    main: ./cmd/turbo
    binary: bin/turbo
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=1
    targets:
      - darwin_amd64
      - darwin_arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}"
archives:
  - id: github
    name_template: 'github/{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    wrap_in_directory: true
    format: tar.gz
    replacements:
      amd64: 64
      386: 32
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
  - id: npm
    name_template: 'npm/{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    wrap_in_directory: false
    format: tar.gz
    replacements:
      amd64: 64
      386: 32
    files:
      - LICENSE
      - src: 'npm/{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}/package.json'
        dst: '/'
        strip_parent: true
      - src: 'npm/{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}/bin/*'
        dst: '/bin/'
        strip_parent: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: vercel
    name: turborepo
  ids:
    - github
  prerelease: auto
  disable: true
publishers:
  - name: npm
    ids:
     - npm
    cmd: 'npm publish{{ if .Prerelease }} --tag canary{{ end }} {{ abs .ArtifactPath }} --dry-run'
