name: "Install Global Turbo"
description: "Installs turbo globally. Expects Node and npm to already be installed"
inputs:
  turbo-version:
    description: The version of turbo to install
    default: 1.13.4-canary.5

runs:
  using: "composite"
  steps:
    - name: Install Turbo globally
      shell: bash
      # Until we are migrate ourselves to 2.0 we pin to the latest 1.x release
      run: |
        VERSION=$(npm view turbo --json | jq -r '.versions | last')
        echo "Latest published version: $VERSION"
        npm i -g turbo@${{ inputs.turbo-version }}
