[package]
name = "next-dev-tests"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"
autobenches = false

# don't publish this crate
publish = false

[dependencies]


[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }
