[package]
name = "turborepo-lockfiles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.2"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.86"
thiserror = "1.0.38"
