name: "Setup Capnproto"
description: "Sets up capnproto for the current platform"
inputs:
  target:
    description: "Compilation target"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Setup capnproto for ubuntu"
      if: inputs.target == 'ubuntu'
      shell: bash
      run: sudo apt-get update && sudo apt-get install capnproto

    - name: "Setup capnproto for macos"
      if: inputs.target == 'macos'
      shell: bash
      run: brew install capnp

    - name: "Setup capnproto for Windows"
      if: inputs.target == 'windows'
      shell: bash
      run: choco install capnproto
