name: Benchmark Turborepo

on:
  workflow_dispatch:
  workflow_run:
    # Make sure this matches the name of the workflow in ./github/workflows/turborepo-release.yml.
    workflows: [Turborepo Release]
    types:
      - completed

jobs:
  # benchmark:
  #   name: Run Benchmarks
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/setup-node
  #     - uses: ./.github/actions/setup-go
  #       with:
  #         github-token: "${{ secrets.GITHUB_TOKEN }}"

  #     - uses: ./.github/actions/setup-turborepo-environment
  #       with:
  #         target: ubuntu-latest
  #         github-token: "${{ secrets.GITHUB_TOKEN }}"

  #     - name: Build
  #       run: cd cli && make turbo-prod

  #     - name: Run benchmarks
  #       run: pnpm -F benchmark benchmark

  #     - name: Save to Tinybird
  #       run: |
  #         curl \
  #           -i \
  #           -F "ndjson=@./benchmark/tinybird.ndjson" \
  #           -X POST \
  #           -H 'Authorization: Bearer ${{ secrets.TINYBIRD_TOKEN }}' \
  #           'https://api.us-east.tinybird.co/v0/datasources?format=ndjson&name=turbo_benchmarks&mode=append'

  time-to-first-task:
    name: Time to First Task
    timeout-minutes: 60
    runs-on: ${{ matrix.os.runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu
            runner: ubuntu-latest
          - name: macos
            runner: macos-latest
          - name: windows
            runner: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      # - uses: ./.github/actions/setup-go
      #   with:
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"

      # - uses: ./.github/actions/setup-turborepo-environment
      #   with:
      #     target: ubuntu-latest
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"

      # - name: Build
      #   run: cd cli && make turbo-prod

      # - name: Clone Fixture
      #   run: cd benchmark && node -r esbuild-register src/setup-ttft.ts

      # - name: Run benchmarks
      #   run: pnpm -F benchmark ttft

      - name: Augment ttft data
        run: |
          node -r esbuild-register ./benchmark/src/ttft-augment.ts ./benchmark/ttft.json ${{github.run_id}}

      # - name: Add Github Action Run URL to JSON
      #   run: |
      #     mv ./benchmark/ttft.json ./benchmark/ttft.json.bak
      #     jq '. + {"url": "https://github.com/vercel/turbo/actions/runs/${{ github.run_id }}"}' ./benchmark/ttft.json.bak > ./benchmark/ttft.json
      #     cat ./benchmark/ttft.json

      # - name: Add SHA to JSON
      #   run: |
      #     mv ./benchmark/ttft.json ./benchmark/ttft.json.bak
      #     jq '. + {"sha": "${{ github.sha }}"}' ./benchmark/ttft.json.bak > ./benchmark/ttft.json
      #     cat ./benchmark/ttft.json

      - name: Save to Tinybird
        run: |
          myjson=$(cat ./benchmark/ttft.json | jq -c)
          echo $myjson
          curl --retry 3 -i -X POST -d "$myjson" -H "Authorization: Bearer ${{ secrets.TINYBIRD_TOKEN }}" https://api.us-east.tinybird.co/v0/events?name=turborepo_perf_ttft

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: profile.json
          path: ./benchmark/profile.json
