name: Check Code Style
on:
  push:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No check run required"'
  clippy:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No clippy run required"'
  fmt:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No fmt run required"'
