name: Large Repo Benchmark

on: workflow_dispatch

permissions:
  pull-requests: write

jobs:
  build:
    name: Run Benchmarks
    timeout-minutes: 40
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
        id: go

      - name: Build
        run: cd cli && make turbo

      - name: Setup Node.js environment
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: cd benchmark && yarn

      - name: Run benchmarks
        run: cd benchmark && yarn benchmark

      - name: Store Benchmark Result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "${{ runner.os }} Benchmark"
          # What benchmark tool the output is formatted as
          tool: "customSmallerIsBetter"
          output-file-path: ./benchmark/benchmarks.json
          benchmark-data-dir-path: benchmarks/large-repo/${{ runner.os }}
          auto-push: ${{ github.event_name == 'push' }}
          comment-on-alert: true
          comment-always: true
          # GitHub API token to make a commit on push, and a comment always
          github-token: ${{ secrets.GITHUB_TOKEN }}
