name: Setup Release Environment

on:
  # Defining workflow_call means that this workflow can be called from
  # your main workflow job
  workflow_call:

jobs:
  greeter:
    runs-on: ubuntu-latest
    # This is optional; it exposes the plan to your job as an environment variable
    env:
      PLAN: ${{ inputs.plan }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-turborepo-environment
